In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

%matplotlib inline
matplotlib.rcParams.update({'font.size': 16})
np.set_printoptions(precision=2,suppress=True)

# Simple SIR Model

$X_k = X_0 \cdot A^k$

In [11]:
# size of the population
num_pop = 1000.

# number of infected individuals
num_infect = 2.

# Define the SIR matrix (entries are probabilities)
sir_mat = np.array([[0.8, 0.2, 0., 0.],
                    [0., 0.5, 0.4, 0.1],
                    [0., 0., 1., 0.],
                    [0., 0., 0., 1.]])

# Define the initial state vector (entries are numbers of people)
x = np.array([num_pop-num_infect,num_infect,0.,0.], ndmin=2)

print('Initial state vector X_0:\n{}'.format(x))
print('\nSIR Update Model:\n{}'.format(sir_mat))

Initial state vector X_0:
[[998.   2.   0.   0.]]

SIR Update Model:
[[0.8 0.2 0.  0. ]
 [0.  0.5 0.4 0.1]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]


In [13]:
n_steps = 20
for s in range(n_steps):
  temp = np.dot(x, sir_mat)
  x=temp
print(x)

[[ 11.51   7.67 784.66 196.16]]


# SIR Model - v2

A more accurate (but still pretty simple) SIR model follows:

* $S_{n+1}=S_n(1-\frac{\beta}{N}I_n)$

* $I_{n+1}=I_n(1+\frac{\beta}{N}S_n-\gamma-\alpha)$

* $R_{n+1}=R_n+\gamma I_n$

* $D_{n+1}=D_n+\alpha I_n$

where $\beta$ represents the probability of an S person becoming infected upon contact with an I, $\gamma$ is the probability of an I person recovering, and $\alpha$ is the probability of an I person dying.  Note that $1/\gamma$ is the average length of the infection period.

In [0]:
# size of the population
num_pop = 1000.

# number of infected individuals
num_infect = 5.

beta = 0.2
gamma = 0.15
alpha = 0.01

S = num_pop-num_infect
I = num_infect
R = 0
D = 0

In [22]:
n_steps = 200
for s in range(n_steps):
    St=S*(1-beta/num_pop*I)
    It=I*(1+beta/num_pop*S-gamma-alpha)
    Rt=R+gamma*I
    Dt=D+alpha*I
    S=St
    I=It
    R=Rt
    D=Dt
    # YOUR CODE HERE
print('S: ',S,' I: ',I,' R: ',R,' D: ',D)

S:  614.466431630447  I:  0.6398872676400746  R:  360.8378260330433  D:  24.055855068869576
